#!/usr/bin/env bash

if [[ "$#" -eq 0 ]]; then
    printf '%s\n' "You must provide at least one argument."
    printf '%s\n' "Example: run fileToExecute.sh"
    exit 1
fi

case $1 in
    *[!/]*)
        cmd=./$1
        ;;
    *)
        cmd=$1
        ;;
esac

shift
"$cmd" "$@"