#!/usr/bin/env bash

set -e

read -erp "Command to search?: " msg

if [[ -z "$msg" ]]; then
  printf '%s\n' "Search cancelled, empty message"
  exit 1
fi

case "$SHELL" in
  */zsh)  grep -aF -- "$msg" "${HISTFILE:-$HOME/.zsh_history}" | sed 's/^: [0-9]*:[0-9]*;//' ;;
  *)      grep -F -- "$msg" "${HISTFILE:-$HOME/.bash_history}" ;;
esac
